/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mando
 */
public class Login1 extends javax.swing.JFrame {

    
      
    /**
     * Creates new form Login1
     */
    public Login1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloSesión = new javax.swing.JLabel();
        Admin_Nuevo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        TxtUsuario = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        Ingresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().setLayout(null);

        TituloSesión.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloSesión.setForeground(new java.awt.Color(255, 255, 255));
        TituloSesión.setText("Iniciar sesión");
        TituloSesión.setToolTipText("");
        getContentPane().add(TituloSesión);
        TituloSesión.setBounds(200, 30, 110, 23);

        Admin_Nuevo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        Admin_Nuevo.setForeground(new java.awt.Color(0, 204, 204));
        Admin_Nuevo.setText("¿Administrador Nuevo?");
        getContentPane().add(Admin_Nuevo);
        Admin_Nuevo.setBounds(320, 220, 150, 20);

        usuario.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(153, 255, 102));
        usuario.setText("Usuario:");
        getContentPane().add(usuario);
        usuario.setBounds(150, 70, 60, 30);

        Registrar.setText("¡Registrar!");
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(Registrar);
        Registrar.setBounds(340, 250, 90, 23);

        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUsuario);
        TxtUsuario.setBounds(180, 100, 140, 30);

        pass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(153, 255, 102));
        pass.setText("Password:");
        getContentPane().add(pass);
        pass.setBounds(150, 140, 60, 20);
        getContentPane().add(TxtPassword);
        TxtPassword.setBounds(180, 160, 140, 30);

        Ingresar.setText("Ingresar");
        getContentPane().add(Ingresar);
        Ingresar.setBounds(190, 210, 73, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mando\\Desktop\\Butacas.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 310);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-513)/2, (screenSize.height-343)/2, 513, 343);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
     
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        
    }//GEN-LAST:event_RegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Nuevo;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel TituloSesión;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
